[server]
# Server name will be displayed in the wallet when connecting
name = "MyServer"
# It may be empty unless you want to list your server in https://walletconnect.com/registry
id = ""
# Server description may be displayed in the wallet when connecting
description = "Change it in config.yml"
# Server icon may be displayed in the wallet when connecting
icons = []
# Server URL may be displayed in the wallet when connecting
url = "https://example.com"

[auth]
server = "auth"

[rpc]
url = "<rpc url>"

[messages]
timeout = "<red>Timeout. Please, log in faster</red>"
rejected = "<red>Please connect to the server in your wallet</red>"
message-to-sign = "My name is <player_name> and I'm signing in to <server> at <time>"
sign-rejected = "<red>Please sign the message</red>"
invalid-signature = "<red>Invalid signature</red>"
different-account = "<red>Please login with account <white><account>...</white></red>"
send-transaction-title = "<gold>Confirm the transaction</gold>"
send-transaction-subtitle = "<green>Open your wallet and confirm your transaction</green>"
transaction-success = "<gold>==============================</gold><newline><green>Success! <hover:show_text:'<gray>Click to open</gray>'><click:open_url:'https://etherscan.io/tx/<tx_hash>'><blue><u>View on etherscan</u></blue></click></hover></green><newline><gold>==============================</gold>"
transaction-error = "<gold>==============================</gold><newline><red>Error! <error> <hover:show_text:'<gray>Click to open</gray>'><click:open_url:'https://discord.gg/'><blue><u>Get help on Discord</u></blue></click></hover></red><newline><gold>==============================</gold>"
not-connected = "<red>Your wallet is not connected! <blue><hover:show_text:'Click to connect'><click:run_command:/connect><u>Connect</u></click></hover></blue></red>"
